# Generated by Django 4.0.5 on 2022-09-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Global_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(blank=True, max_length=250)),
                ('tg_chat_id', models.IntegerField()),
                ('vacancy_name', models.CharField(blank=True, max_length=250)),
                ('vacancy_name_durty', models.CharField(blank=True, max_length=250)),
                ('sity', models.CharField(blank=True, max_length=250)),
                ('salary_min', models.IntegerField(default=0)),
                ('salary_max', models.IntegerField(default=0)),
                ('start_when', models.CharField(blank=True, max_length=250)),
                ('only_with_salary', models.BooleanField(default=False)),
                ('start_when_unix', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('url', models.CharField(blank=True, max_length=250)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('vac_id', models.IntegerField(primary_key=True, serialize=False)),
                ('published_day', models.CharField(blank=True, max_length=250)),
                ('published_time', models.CharField(blank=True, max_length=250)),
                ('user', models.CharField(blank=True, max_length=250)),
                ('tg_id', models.IntegerField(default=0)),
                ('is_shown', models.BooleanField(default=False)),
            ],
        ),
    ]
