# Generated by Django 4.0.5 on 2022-07-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers_and_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_users',
            name='start_when',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
