# Generated by Django 4.0.5 on 2022-09-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers_and_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='global_users',
            old_name='user_name',
            new_name='for_user',
        ),
    ]
