# Generated by Django 4.0.5 on 2022-09-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers_and_bot', '0002_rename_user_name_global_users_for_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='user',
            new_name='for_user',
        ),
    ]
