# Generated by Django 4.0.5 on 2022-07-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers_and_bot', '0003_alter_global_users_salary_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='for_user',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
