# Generated by Django 4.0.5 on 2022-07-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers_and_bot', '0004_alter_vacancy_for_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='for_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers_and_bot.global_users'),
        ),
    ]
