# Generated by Django 4.0.5 on 2022-07-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers_and_bot', '0006_rename_name_global_users_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='global_users',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='user_name',
            new_name='for_user',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='vac_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='tg_chat_id',
            new_name='tg_id',
        ),
    ]
