# Generated by Django 4.0.5 on 2022-07-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers_and_bot', '0007_rename_user_name_global_users_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['for_user']},
        ),
    ]
