# Generated by Django 4.0.5 on 2022-07-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers_and_bot', '0008_alter_vacancy_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='global_users',
            old_name='name',
            new_name='for_user',
        ),
    ]
