name: Docker Image CI

on: [push]

jobs:

build:

runs-on: ubuntu-latest
env:
DATABASE_URL: postgres://django_user:12345wW!@localhost:5432/django_db
DJANGO_SETTINGS_MODULE: job_filter_app.settings
SECRET_KEY: refwekj4kj54kj35nr43fj34f42lf4
PORT: 8000
PG_DB: django_db
PG_PASS: 12345wW!
PG_USER: django_user

steps:
- uses: actions/checkout@v1
- name: Build the docker-compose stack
run: docker-compose up -d
- name: Sleep
uses: jakejarvis/wait-action@master
with:
time: '60s'
- name: Check running containers
run: docker ps
- name: Run test suite
run: docker exec backend pytest --skip-auth